name: Docker Dev CD

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - '**.go'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/matteocarnelos/kadlab:${GITHUB_REF#refs/heads/}
          
