name: Docker CD

on:
  push:
    paths:
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - '**.go'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Create Image Tag
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          if [ $IMAGE_TAG = "main" ]; then IMAGE_TAG="latest"; fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      -
        name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/matteocarnelos/kadlab:${{ env.IMAGE_TAG }}
          
